# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='tipo',
            field=models.CharField(choices=[('funcional', 'Funcional'), ('dados', 'Dados')], default=None, max_length=255),
        ),
    ]
