# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisito', '0003_auto_20171202_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
