# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisito', '0005_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='dev_id',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='req_id',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
