# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise_de_requisitos', '0001_initial'),
        ('requisito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desenvolvedores', to='analise_de_requisitos.AnaliseDeRequisitos')),
                ('dev_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='desenvolvedor.Desenvolvedor')),
            ],
        ),
        migrations.AddField(
            model_name='atividades',
            name='dev_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='desenvolvedor.Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desenvolvedores', to='requisito.Requisito'),
        ),
    ]
