# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvedor', '0005_auto_20171202_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='ar_id',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='dev_id',
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
