# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvedor', '0007_auto_20171202_2030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='desenvolvedor',
            table='desenvolvedor',
        ),
    ]
