# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0005_auto_20171203_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividade',
            table='atividade',
        ),
    ]
